# Generated by Django 3.1.4 on 2021-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='codigo_banco',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código do Banco'),
        ),
    ]
